name: ventricle
channels:
- fastai
- pytorch
dependencies:
- fastai==1.0.55
- pytorch==1.0.1
- pip
- pip:
<<<<<<< HEAD
    - ipyexperiments
=======
        - ipyexperiments
>>>>>>> e7319fcaf6f13c490137803db24084987acde497
